DATA SEGMENT
ASCSTG DB '5', 'A', '6', '1'
BIN DB 2 DUP(0)
DATA ENDS
STACK SEGMENT 
DB 100 DUP(?)
STACK ENDS
CODE SEGMENT
ASSUME CS: CODE, DS: DATA, SS: STACK
ASCB: MOV AX, DATA
MOV DS, AX
MOV CL, 4
MOV CH, CL
MOV SI, OFFSET ASCSTG
CLD
XOR AX, AX
XOR DX, DX
ASCB1: LODS ASCSTG
AND AL, 7FH
CMP AL, '0'
JL ERROR
CMP AL, '9'
JG ASCB2
SUB AL, 30H
JMP SHORT ASCB3
ASCB2: CMP AL, 'A'
JL ERROR
CMP AL, 'F'
JG ERROR
SUB AL, 37H
ASCB3: OR DL, AL
ROR DX, CL
DEC CH
JNZ ASCB1
MOV WORD PTR BIN, DX
HLT
CODE ENDS 
END ASCB
